### ISSUE TITLE
I'm very interested, but I can't run successfully

### ISSUE THREAD

**Issue by yuzd** [kevingosse/ManagedDotnetGC#1]
[Loader] Loading module
[Loader] Successfully loaded ManagedDotnetGC.dll
[Loader] Fowarding call to GC_VersionInfo
Failed to create CoreCLR, HRESULT: 0x80004005
[Loader] Detaching ManagedDotnetGC loader

**Comment by lap1nou** [comment]
Hello @yuzd,

May I ask you if you found a solution for this problem ? I got the same error and trying to figure out why.

Regards.
